// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'
// lang.js
export const SET_LOCALE = 'SET_LOCALE'

//car.js
export const FETCH_CARS = 'FETCH_CARS'
export const FETCH_CARS_FAILURE = 'FETCH_CARS_FAILURE'
export const FETCH_CARS_SUCCESS = 'FETCH_CARS_SUCCESS'
export const FETCH_CARS_LOCATION_SUCCESS = 'FETCH_CARS_LOCATION_SUCCESS'
//route.js
export const FETCH_LOCATIONS = 'FETCH_LOCATIONS'
export const FETCH_LOCATIONS_FAILURE = 'FETCH_LOCATIONS_FAILURE'
export const FETCH_LOCATIONS_SUCCESS = 'FETCH_LOCATIONS_SUCCESS'

//book.js
export const FETCH_BOOKING = 'FETCH_CARS'
export const FETCH_BOOKING_FAILURE = 'FETCH_BOOKING_FAILURE'
export const FETCH_BOOKING_SUCCESS = 'FETCH_BOOKING_SUCCESS'
export const FETCH_BOOK_PICKUP_LOCATION_SUCCESS = 'FETCH_BOOK_PICKUP_LOCATION_SUCCESS'
export const FETCH_BOOK_PICKUP_LOCATION_FAILURE = 'FETCH_BOOK_PICKUP_LOCATION_FAILURE'
export const FETCH_BOOK_DROPOFF_LOCATION_SUCCESS = 'FETCH_BOOK_DROPOFF_LOCATION_SUCCESS'
export const FETCH_BOOK_DROPOFF_LOCATION_FAILURE = 'FETCH_BOOK_DROPOFF_LOCATION_FAILURE'
export const FETCH_BOOK_HISTORY = 'FETCH_BOOK_HISTORY'
export const FETCH_BOOK_HISTORY_SUCCESS = 'FETCH_BOOK_HISTORY_SUCCESS'
export const FETCH_BOOK_HISTORY_FAILURE = 'FETCH_BOOK_HISTORY_FAILURE'
export const GET_BOOK_HISTORY_URL = 'GET_BOOK_HISTORY_URL'

//Carlo - driver.js 2/17/21
export const FETCH_DRIVERS_SUCCESS = 'FETCH_DRIVERS_SUCCESS'
export const FETCH_DRIVERS_FAILURE = 'FETCH_DRIVERS_FAILURE'